
version: '3.9'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    networks:
      - local
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  migrate:
    image: migrate/migrate
    depends_on:
      clickhouse:
        condition: service_healthy

    networks:
      - local
    volumes:
      - ./clickhouse/migrations:/migrations
    command:
      [ "-database",
        "clickhouse://clickhouse:9000?username=default&database=default&x-multi-statement=true",
        "-path", "/migrations", "up" ]


  app:

    healthcheck:
      test: wget --spider http://localhost:8080/healtz
      interval: 10m

    depends_on:
      migrate:
        condition: service_completed_successfully

    networks:
      - local

    build:
      dockerfile: Dockerfile

    command:
      - "-log=/logs/log.txt"

    ports:
      - "8080:8080"

    env_file: .env

    environment:
      CLICKHOUSE_ADDRESS: clickhouse:9000

networks:
  local:
    driver: bridge
